version: "3.7"

services:
  nitter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nitter
    hostname: nitter
    ports:
      - '127.0.0.1:8012:8080'
    volumes:
      - ./nitter.conf:/src/nitter.conf:Z,ro
    depends_on:
      - nitter-redis
    restart: always
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    user: "998:998"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  nitter-redis:
    image: redis:latest
    container_name: nitter-redis
    hostname: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./nitter-redis:/data
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
    user: "999:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  nitter-redis:
